name: Build APK with Buildozer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            python3-setuptools \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            libffi-dev \
            libssl-dev \
            liblzma-dev \
            libbz2-dev \
            libreadline-dev \
            libsqlite3-dev

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install cython==0.29.36 buildozer==1.5.0

      - name: Build APK
        run: |
          buildozer init || true
          buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Driver4U-debug-apk
          path: bin/*.apk
