name: Build APK with Buildozer

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          # Remove cache setting since we don't have requirements.txt

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            python3-setuptools \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            libffi-dev \
            libssl-dev \
            liblzma-dev \
            libbz2-dev \
            libreadline-dev \
            libsqlite3-dev \
            autoconf \
            automake \
            libtool \
            pkg-config \
            zlib1g-dev

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install cython==0.29.36 buildozer==1.5.0

      - name: Initialize Buildozer if needed
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
            echo "Created default buildozer.spec file"
          else
            echo "Using existing buildozer.spec file"
          fi

      - name: Build APK
        run: |
          buildozer -v android debug
        env:
          # Set environment variables to avoid interactive prompts
          CI: true
          BUILDOZER_NO_UPDATE: true

      - name: Check if APK was created
        run: |
          if ls bin/*.apk 2>/dev/null; then
            echo "APK built successfully"
          else
            echo "Error: No APK file found in bin directory"
            exit 1
          fi

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Driver4U-debug-apk
          path: bin/*.apk
          retention-days: 7

      - name: Clean up
        if: always()
        run: |
          # Clean up to save space
          buildozer android clean || true
